### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by graywolf336** [rogermb/BukkitSpeak#2]
When doing the command "/tsa ban Graywolf Bye." I get the following in the console: 

``` java
2012-08-30 23:57:40 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'tsa' in plugin BukkitSpeak v0.55
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:601)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:878)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:825)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:807)
    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:107)
    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:44)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:276)
    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109)
    at org.getspout.spout.SpoutNetServerHandler.d(SpoutNetServerHandler.java:173)
    at net.minecraft.server.ServerConnection.b(SourceFile:35)
    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:608)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:244)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:501)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:419)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.NullPointerException
    at net.but2002.minecraft.BukkitSpeak.Commands.BukkitSpeakCommand.replaceKeys(BukkitSpeakCommand.java:166)
    at net.but2002.minecraft.BukkitSpeak.Commands.CommandBan.execute(CommandBan.java:62)
    at net.but2002.minecraft.BukkitSpeak.BukkitSpeakCommandExecutor.onTeamspeakAdminCommand(BukkitSpeakCommandExecutor.java:134)
    at net.but2002.minecraft.BukkitSpeak.BukkitSpeakCommandExecutor.onCommand(BukkitSpeakCommandExecutor.java:51)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
    ... 17 more
```

**Comment by rogermb** [comment]
I'm aware that the ban command is still (extremely) buggy, due to a lack of people willing to get banned on my TS3 I use for testing :D

I'm at the moment doing some quite big code refractors which I don't commit every single time, but I think you can expect a working /tsa ban in the next update.

Sorry for the inconveniance.

**Comment by graywolf336** [comment]
Okay thanks.
